### ISSUE TITLE
#gelrand

### ISSUE THREAD

**Issue by UserNaem** [twiforce/fukuro#16]
Steps to reproduce:
Try posting with:
#gelrand:"patchouli_knowledge solo score:>2 rating:safe -plump -breasts -comic -greyscale -translation_request"
Expected results:
The post should contain a random picture fitting this search request
Actual results:
![image](https://cloud.githubusercontent.com/assets/21028464/22856632/c9d92fc0-f0b6-11e6-8ded-d732a67e8dc0.png)

(The tags are valid and there are over 16 pages of results for this search request)

**Comment by twiforce** [comment]
Fixed here https://github.com/twiforce/fukuro/commit/e1a35b3b0acd7502734cf641abf26ebce0452122
