### ISSUE TITLE
Webm/video module

### ISSUE THREAD

**Issue by HarukoKisaragi** [twiforce/fukuro#19]
Good day

It seem like there is no video module in this build for webm/mp4, only "An unknown error occured when posting!" - error. Does it possible to turn it on (in settings, maybe) / add module without any problems with config?

thx

**Comment by twiforce** [comment]
Hi,
You should install some ffmpeg on your server to get this properly working, as far as I remember.

**Comment by HarukoKisaragi** [comment]
Okay, thx
